### ISSUE TITLE
'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by obeewnn** [suyashkumar/seven-segment-ocr#1]
Hi, would you be able to help with the error below?

```
Traceback (most recent call last):
  File "seven_segment_ocr.py", line 59, in <module>
    digitsReadArray = read_video_digits(args.video, args.period)
  File "seven_segment_ocr.py", line 20, in read_video_digits
    selections=image_selection.getSelectionsFromImage(image)
  File "C:\obtv\seven-segment-ocr\image_selection.py", line 40, in getSelectionsFromImage
    clone = image.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by suyashkumar** [comment]
Sorry about the delay, I haven't really been maintaining this anymore -- did you make sure to click and drag the mouse to select the display digit(s) in the video?
